### ISSUE TITLE
Working but after a while...

### ISSUE THREAD

**Issue by Friends4U** [letsencrypt-cpanel/letsencrypt-cpanel-dnsonly#2]
After a while it's gives the following error:

From: **Cron <root@ns2> /usr/local/letsencrypt-cpanel-dnsonly/acmetool --batch reconcile**

```
20171201135503 [ERROR] acme.storageops: Target(ns2.myhostname.nl;https://acme-v01.api.letsencrypt.org/directory;0): failed to request certificate: cannot prompt the user: currently non-interactive

20171201135503 [ERROR] acme.storageops: error while processing targets: the following errors occurred:

error satisfying Target(ns2.myhostname.nl;https://acme-v01.api.letsencrypt.org/directory;0): cannot prompt the user: currently non-interactive

20171201135503 [ERROR] acme.storageops: failed to reconcile: the following errors occurred:

error satisfying Target(ns2.myhostname.nl;https://acme-v01.api.letsencrypt.org/directory;0): cannot prompt the user: currently non-interactive

20171201135504 [CRITICAL] acmetool: fatal: reconcile: the following errors occurred:

error satisfying Target(ns2.myhostname.nl;https://acme-v01.api.letsencrypt.org/directory;0): cannot prompt the user: currently non-interactive

```
What can I do about this? I replaced my original hostname with myhostname.

**Comment by alexzorin** [comment]
See the docs under "I want to run renewal by hand or troubleshoot the renewal process". This is because Let's Encrypt changed their terms of service recently and acmetool wants to interactively confirm that you agree to the new subscriber agreement.

I have updated the rpm to v 0.0.2 which will automatically agree to the latest subscriber agreement, but you can also just do the above.
