### ISSUE TITLE
Set e-mail address for receiving certificate expiry notifications from Let's Encrypt

### ISSUE THREAD

**Issue by dimangelid** [letsencrypt-cpanel/letsencrypt-cpanel-dnsonly#4]
Hello,

Currently on some cPanel DNSONLY servers i manage, i manually install and renew Let's Encrypt certificates by using certbot.

When i install a certificate for the first time, at the certbot command i insert the e-mail address Let's Encrypt will use in order to send me notifications about the certificate expiry. That is very convenient, in order not to forget renewing a certificate.

I am not able to find such option either at your module, or at acmetool .

Is anyone aware of such an option?

**Comment by alexzorin** [comment]
When an ACME account is registered with Let's Encrypt, you generally have the option of attaching an email address to it. If an email address is attached, then the "Let's Encrypt Expiry Bot" will send you emails about certificates that are expiring.

With this project in particular, no email address is offered. More specifically, a blank email address is always set, shown in the responses.yml file:

https://github.com/letsencrypt-cpanel/letsencrypt-cpanel-dnsonly/blob/14e20e7edf90e90a4a3a30e31064b1d3b00ced07/responses.yml#L1

At the moment there's no way to override this that I can think of. It's kind of problematic because the installer is meant to be non-interactive.

I would prefer to solve this by adding the ability to update the registration email address in acmetool, which [has an open issue](https://github.com/hlandau/acme/issues/284) but hasn't had any work done on it yet.

Some workarounds:
- acmetool will send you an email (via cron) if it fails to renew the DNSONLY certificate, 30 days before expiration and every attempt after that, which could be considered a substitute for this functionality
- You could use something like Uptime Robot to monitor the https://$(hostname):2087 endpoint, and it will warn you if the certificate is getting close to expiring

I agree that this would be a nice enhancement but I'm a bit busy recently so it's not likely I'll do this soon. I'd be happy to accept a pull request (such as overwriting the email address responses.yml with an environment variable from the system, if present).

**Comment by alexzorin** [comment]
I'm closing this because this project was re-written (see the website for details) and you can nominate an email address before installing:

    echo "FLEETSSL_DNSONLY_ACME_EMAIL_ADDRESS=me@example.com" >> /etc/fleetssl-dnsonly.conf
